# Generated by Django 5.2.10 on 2026-01-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_origin'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='authenticity',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
